name: second-workflow
on: [push, pull_request]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Linter with pylint
        run: pipenv run pylint app
      - name: Launch test
        run: pipenv run nosetests
